const http = require('http');
const { Pool } = require('pg');
const PORT = process.env.PORT || 10000;
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false }, max: 3 }) : null;
const monthKey = () => { const d=new Date(); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`; };
async function init(){ if(!pool) return; await pool.query(`CREATE TABLE IF NOT EXISTS leaderboard_users (discord_id TEXT PRIMARY KEY, username TEXT NOT NULL, avatar TEXT, month_key TEXT NOT NULL, minutes INTEGER NOT NULL DEFAULT 0, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE INDEX IF NOT EXISTS leaderboard_month_idx ON leaderboard_users(month_key, minutes DESC);`); }
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>10000)req.destroy();});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'));}catch(e){reject(e);}});req.on('error',reject);});}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return json(res,204,{});try{if(req.url==='/health')return json(res,200,{ok:true,service:'skynix-leaderboard'});if(!pool)return json(res,503,{success:false,error:'DATABASE_URL yapılandırılmadı'});if(req.method==='POST'&&req.url==='/leaderboard/heartbeat'){const x=await body(req);if(!x.discordId||!x.username)return json(res,400,{success:false,error:'discordId ve username gerekli'});const minutes=Math.max(0,Math.min(5,Math.floor(Number(x.minutes)||0)));await pool.query(`INSERT INTO leaderboard_users(discord_id,username,avatar,month_key,minutes) VALUES($1,$2,$3,$4,$5) ON CONFLICT(discord_id) DO UPDATE SET username=EXCLUDED.username,avatar=EXCLUDED.avatar,month_key=EXCLUDED.month_key,minutes=CASE WHEN leaderboard_users.month_key=EXCLUDED.month_key THEN leaderboard_users.minutes+EXCLUDED.minutes ELSE EXCLUDED.minutes END,updated_at=NOW()`,[String(x.discordId),String(x.username).slice(0,80),x.avatar||null,monthKey(),minutes]);return json(res,200,{success:true});}if(req.method==='GET'&&req.url==='/leaderboard/monthly'){const q=await pool.query(`SELECT discord_id AS "discordId",username,avatar,minutes FROM leaderboard_users WHERE month_key=$1 ORDER BY minutes DESC, updated_at ASC LIMIT 100`,[monthKey()]);return json(res,200,{success:true,month:monthKey(),users:q.rows});}return json(res,404,{error:'Not found'});}catch(e){console.error(e);return json(res,500,{success:false,error:'Sunucu hatası'});}});
init().then(()=>server.listen(PORT,()=>console.log(`Skynix leaderboard listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1);});