const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  windowControl:              (action)          => ipcRenderer.send('window-action', action),
  selectLolExe:               ()                => ipcRenderer.invoke('select-lol-exe'),
  selectSkinFile:             ()                => ipcRenderer.invoke('select-skin-file'),
  selectSkinFolder:           ()                => ipcRenderer.invoke('select-skin-folder'),
  copyToInstalled:            (sourcePath)      => ipcRenderer.invoke('copy-to-installed', sourcePath),
  importSkinToInstalled:      (sourcePath)      => ipcRenderer.invoke('import-skin-to-installed', sourcePath),
  detectSkinChamp:            (skinPath)        => ipcRenderer.invoke('detect-skin-champ', skinPath),
  getPathForFile:             (file)            => webUtils ? webUtils.getPathForFile(file) : file.path,
  autoDetectLol:              ()                => ipcRenderer.invoke('auto-detect-lol'),
  scanInstalledSkins:         ()                => ipcRenderer.invoke('scan-installed-skins'),
  runCslolSkin:               (data)            => ipcRenderer.invoke('run-cslol-skin', data),
  stopCslolSkin:              ()                => ipcRenderer.invoke('stop-cslol-skin'),
  deleteInstalledSkin:        (skinPath)        => ipcRenderer.invoke('delete-installed-skin', skinPath),
  clearInstalledSkins:        ()                => ipcRenderer.invoke('clear-installed-skins'),
  selectDbFolder:             ()                => ipcRenderer.invoke('select-db-folder'),
  autoDetectDbFolder:         ()                => ipcRenderer.invoke('auto-detect-db-folder'),
  findDbSkinFile:             (data)            => ipcRenderer.invoke('find-db-skin-file', data),
  onCslolLog:                 (callback)        => ipcRenderer.on('cslol-log', (event, msg) => callback(msg)),
  onLolStatusChange:          (callback)        => ipcRenderer.on('lol-status-change', (event, isRunning) => callback(isRunning)),
  updatePresence:             (state, details)  => ipcRenderer.send('update-presence', { state, details }),
  discordLogin:               ()                => ipcRenderer.invoke('discord-oauth-login'),
  downloadStoreModFile:       (data)            => ipcRenderer.invoke('download-store-mod-file', data),
  exportSkinFile:             (sourcePath, defaultName) => ipcRenderer.invoke('export-skin-file', { sourcePath, defaultName }),
  openSkyfixer:               (skinPath)        => ipcRenderer.invoke('open-skyfixer', skinPath),
  runSkyfixer:                (skinPath)        => ipcRenderer.invoke('run-topaz-skyfixer', skinPath),
  getSkyfixerStatus:          (skinPath)        => ipcRenderer.invoke('get-skyfixer-status', skinPath),
  onSkyfixerProgress:         (callback)        => ipcRenderer.on('skyfixer-progress', (event, data) => callback(data)),
  syncDbFromGithub:           ()                => ipcRenderer.invoke('sync-db-from-github'),
  onSyncDbProgress:           (callback)        => ipcRenderer.on('sync-db-progress', (event, data) => callback(data)),
  checkAppUpdate:             ()                => ipcRenderer.invoke('check-app-update'),
  getAppVersion:              ()                => ipcRenderer.invoke('get-app-version'),
  downloadAndInstallUpdate:   (data)            => ipcRenderer.invoke('download-and-install-update', data),
  onAppUpdateDownloadProgress:(callback)        => ipcRenderer.on('app-update-download-progress', (event, data) => callback(data)),
  // ── TRAY & NOTIFICATION ─────────────────────────────────────────────────────
  setSkinRunningState:        (running)         => ipcRenderer.send('set-skin-running-state', running),
  showSkinStartedNotification:(lang)            => ipcRenderer.send('show-skin-started-notification', lang),
  onTrayStartSkins:           (callback)        => ipcRenderer.on('tray-start-skins', () => callback()),
  onTrayStopSkins:            (callback)        => ipcRenderer.on('tray-stop-skins', () => callback()),
  // ── IN-GAME OPTİMİZASYON ────────────────────────────────────────────────────
  onInGameOptimization:       (callback)        => ipcRenderer.on('in-game-optimization', (event, isActive) => callback(isActive))
});
